### ISSUE TITLE
Défilement clavier slide

### ISSUE THREAD

**Issue by philicorne** [devpratico/pratico#67]
Pouvoir défiler avec les flèches du clavier

**Comment by tomx-sh** [comment]
Voilà la situation : on veut utiliser les flèches du clavier pour naviguer d'une page à l'autre, mais malheureusement TLDraw s'accapare la gestion du clavier, et donc actuellement quand on appuie sur les flèches, ça sert à déplacer la forme actuellement sélectionnée sur le Canvas (et quand rien n'est sélectionné il se passe rien).

On pourrait désactiver les raccourcis clavier de TLDraw, mais malheureusement on perdrait tous les raccourcis pratiques (voire indispensables) qui sont le 'supprimer' qui supprime la forme, le copier coller, ctrl+Z etc.

Donc on aimerait pouvoir défiler les slides avec le clavier, sans perdre les features de TLDraw.
Ça veut donc dire à mon avis, trouver un moyen de 'personnaliser' Tldraw.

La doc Tldraw : https://tldraw.dev/quick-start

Le principal composant de TLDraw c'est `<Tldraw>`,  c'est donc le tableau blanc avec les outils. Moi j'ai préféré appeler ça des `<Canvas>` et j'en ai créé plusieurs dans l'app (pour le formateur, pour l'apprenant, quand la session est en cours etc.)
La bonne nouvelle c'est qu'elles sont toutes un wrapper de celui qui est dans _app/(frontend)/[locale]/\_components/canvases/Canvas.tsx_
Tous les Canvas de l'appli sont basés sur celui-ci (normalement), auquel j'ai appliqué tout un tas de réglages que je voulais.

Là dedans, c'est Tldraw qui gère des raccourcis claviers (copier coller, supprimer etc). Et si je dis pas de bêtise c'est grâce au hook `useKeyboardShortcuts()` que j'ai wrappé dans `<KeyboardShortcuts/>` et placé comme enfant de _Canvas.tsx_. Donc je crois que si tu l'enlèves, y'a plus de raccourcis clavier TLdaw du tout (à confirmer ?).

Il ne semble pas y avoir de personnalisation possible de ce hook, mais à voir dans la doc si il existe une solution !
